#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          left,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void movewheel2control(){//motor controlled by two joystick
	motor[port1]=vexRT[Ch2];//setting speed of right motor
	motor[port10]=-vexRT[Ch3];//setting speed of left motor
}
void movewheel(){//motor controlled by one joystick
	float y = vexRT[Ch2]/2;//get joystick value
	//change to left side control 2017/11/10
	float x = vexRT[Ch1]/2;//get joystick value
	//change to left 2017/11/10
	y*=0.9;
	x*=0.9;
	float left_motor;//variable for speed of left motor
	float right_motor;//variable for speed of right motor
	float power, st;//power for speed to distribute, st for steering
	power = sqrt(x*x+y*y);//calculating power
	if(y>=0&&power!=0){//check joystick position of y
		st = x * 100/power;//set value for st
		if(x>=0){//check joystick position of x
			left_motor = power;//set speed
			right_motor = (1-0.02*st)*power;
		}
		else{
			right_motor = power;
			left_motor = (1+0.02*st)*power;
		}
	}
	if(y<=0&&power!=0){
		power*=-1;
		st = x * 100/power;
		if(x>=0){
			left_motor = (1+0.02*st)*power;
			right_motor = power;
		}
		else{
			right_motor = (1-0.02*st)*power;
			left_motor = power;
		}
	}
	if(x==0&&y==0){
		motor[port10] = 0;
		motor[port1] = 0;
	}
	motor[port10] = -left_motor;//set speed for left motor
	motor[port1] = right_motor;//set speed for right motor
}

void movearm(){
	/*
	if(vexRT[Btn5U] == 1){//check of button 5U is pressed
		motor[port7] = 75;//lift arm if it does not exceed limit
	}
	else if(vexRT[Btn5D] == 1){//check of button 5D is pressed
		motor[port7] = -50;//lower arm
	}
	else{
		motor[port7] = 15;//prevent arm from falling down due to gravity
	}
	*/
	//2017/11/10 change to joystick control
	if(vexRT[ch3]>-10&&vexRT[ch3]<10){
		motor[port7] = 15;
	}else{
		motor[port7] = vexRT[ch3]/2;
	}
}

void moveclaw(){
	/*
	if(vexRT(Btn6U) == 1){//check of button 6U is pressed
		motor[port6] = 100;//open claw
	}
	else if(vexRT(Btn6D) == 1){//check of button 6D is pressed
		motor[port6] = -25;//close claw
	}else{
		motor[port6] = 0;//assure claw is shut tightly
	}	
	*/
	//change control 2017/11/10
	if(vexRT[Btn6U]==1
		||vexRT[Btn8R]==1)
	{
		motor[port6] = 100;
	}
	else if(vexRT[Btn8D]==1
					||vexRT[Btn6D]==1)
	{
		motor[port6] = -25;
	}else{
		motor[port6] = 0;
	}
}	
/*
void lineFollow(float motor1, float motor10, float difference, float a){
	if(sensorvalue(armstop)==1){//button for safety
			difference = sensorValue(light_right)-sensorValue(light_left);//difference between two light sensor
			motor[port1] = motor1+difference*a;//setting speed of motor, check if robot should turn
			motor[port10] = motor10+difference*a;//setting speed of motor, check if robot should turn
	}else{
			motor[port1] = 0;//stop if button is not pressed
			motor[port10] = 0;//stop if button is not pressed
	}
}
*/
/*void testStraight(){
	motor[port1]=vexRT[ch2];
	motor[port10]=-vexRT[ch2];
}
*/

task main(){
	// variable initializing for line following mechanism
	/*
	float motor1 = 25;//initializing right motor speed
	float motor10 = -25;//initializing left motor speed
	float difference = 0;//difference between two sensor values
	float a = -0.03325//adjusting constant
	*/
	while(true){
		movearm();
		moveclaw();
		movewheel();
	}
}
